### ISSUE TITLE
[Bug/Crash]: Doesn't work on exported game, missing .dll file

### ISSUE THREAD

**Issue by Anything-Games** [vaporvee/discord-sdk-godot#19]
### What happened?

If I play from the editor it works fine, but when exporting my game, it no longer works. I did some testing, and in a new project I saw when exporting the game, 2 .dll files are being created, but on my project only 1 .dll file is being created, which is "discord_game_sdk_binding.dll" I don't understand why this is happening, and guessing this is the reason it doesn't work when exporting, hope you can help.

### Version

1.5

### Godot Version

4.0.2 stable

### GDScript

```gdscript
extends Node


# Called when the node enters the scene tree for the first time.
func _ready():
	set_physics_process(false)
	
	Discord_Activity.app_id = *****REMOVED*****
	print("is discord working: " + str(Discord_Activity.get_is_discord_working()))
	Discord_Activity.details = "Loading into space..."
	Discord_Activity.large_image = "game_icon"
	Discord_Activity.start_timestamp = int(Time.get_unix_time_from_system())
	Discord_Activity.refresh()

var update_timer : float = 15
var update_start_time : float = 10

func _process(delta):
	update_timer -= delta
	if update_timer <= 0:
		update_timer = update_start_time
		update_activity()

func update_activity():
	Discord_Activity.details = "Buying and selling"
	Discord_Activity.state = "Money: "+  str(player_data.money_usd).pad_decimals(2)
	Discord_Activity.refresh()
```

### Additional information

Log file:

USER SCRIPT ERROR: Parse Error: Identifier "Discord_Activity" not declared in the current scope.
   at: GDScript::reload (res://addons/discord-sdk-gd/sdk_utility.gd:4)
USER ERROR: Script does not inherit from Node: res://addons/discord-sdk-gd/sdk_utility.gd.
   at: start (main/main.cpp:2776)
USER SCRIPT ERROR: Parse Error: Identifier "Discord_Activity" not declared in the current scope.
   at: GDScript::reload (res://discord.gd:8)
USER SCRIPT ERROR: Parse Error: Identifier "Discord_Activity" not declared in the current scope.
   at: GDScript::reload (res://discord.gd:9)
USER SCRIPT ERROR: Parse Error: Identifier "Discord_Activity" not declared in the current scope.
   at: GDScript::reload (res://discord.gd:10)
USER SCRIPT ERROR: Parse Error: Identifier "Discord_Activity" not declared in the current scope.
   at: GDScript::reload (res://discord.gd:11)
USER SCRIPT ERROR: Parse Error: Identifier "Discord_Activity" not declared in the current scope.
   at: GDScript::reload (res://discord.gd:12)
USER SCRIPT ERROR: Parse Error: Identifier "Discord_Activity" not declared in the current scope.
   at: GDScript::reload (res://discord.gd:13)
USER SCRIPT ERROR: Parse Error: Identifier "Discord_Activity" not declared in the current scope.
   at: GDScript::reload (res://discord.gd:25)
USER SCRIPT ERROR: Parse Error: Identifier "Discord_Activity" not declared in the current scope.
   at: GDScript::reload (res://discord.gd:26)
USER SCRIPT ERROR: Parse Error: Identifier "Discord_Activity" not declared in the current scope.
   at: GDScript::reload (res://discord.gd:27)

### Checks

- [X] I tried reinstalling the addon in a new project.

**Comment by Anything-Games** [comment]
Okay so I continued to mess around with it, and after making a new export preset it creates both .dll files, not sure if this is intended, a common issue, or just a me problem. Not sure what you want me to do with this issue, I'll leave it open until you reply.

**Comment by vaporvee** [comment]
This is could be a very weird godot bug i assume. There is a export script wich checks for export events and copies the extra dll file in this addon. Did you really just make a new export preset nothing else? Weird would make more sense when this would be fixed with new export template files

**Comment by vaporvee** [comment]
I'll probably add this to a FAQ section in the docs when i'll release 2.0 if this isn't a corrupt template issue

**Comment by Anything-Games** [comment]
> Did you really just make a new export preset nothing else? Weird would make more sense when this would be fixed with new export template files

Yes, I just clicked add new and created a new Windows export (forgot to say what platform before), and it worked, after that I copied over my settings manually one by one and it worked again with my settings, don't really understand it. The project itself worked fine with the other export preset, and that preset is from months ago from before I added the plugin, as I added the plugin yesterday. I will also say, that export preset is probably created with a Godot 4 alpha build, maybe beta, as I started this project when the alpha release of Godot 4, so maybe that could also be something to do with it, but I don't really know.

**Comment by ItsAnysek** [comment]
I also tested this in 1.5 in a new project, using the default Windows Desktop export preset, and it created the two .dll files just fine.

**Comment by vaporvee** [comment]
Oh youset 1.5 already as your version? Because exports where heavily buggy in 1.4

**Comment by ItsAnysek** [comment]
Oh, well, I never tried to export the project before now.

**Comment by vaporvee** [comment]
oh lol sorry i thought you where the first person i was on mobile

**Comment by ItsAnysek** [comment]
So, this is fixed now? Because you closed the issue. OP was also using 1.5.

**Comment by Anything-Games** [comment]
So I just tried exporting my project again, with the new preset, and it is only exporting 1 .dll once again...

Also this error was printed to the console: editor/export/editor_export_plugin.h:125 - Required virtual method EditorExportPlugin::_get_name must be overridden before calling.

**Comment by ItsAnysek** [comment]
> Also this error was printed to the console: editor/export/editor_export_plugin.h:125 - Required virtual method EditorExportPlugin::_get_name must be overridden before calling.

This also happens to me, but only when I load the project and export it for the first time. After that, the error doesn't happen. When I restart the project and export the game for the first time again, the error happens. It doesn't seem to me like it affects anything, though.

**Comment by Anything-Games** [comment]
> This also happens to me, but only when I load the project and export it for the first time. After that, the error doesn't happen. When I restart the project and export the game for the first time again, the error happens. It doesn't seem to me like it affects anything, though.

Okay yeah, this is also true for me, but my 2nd .dll file is still not being exported, so maybe the error isn't relevant to my issue. I might end up either just needing to remember not to delete the 2nd .dll file ever and maybe it won't need a new one every time, or just remove the plugin and forget about using it for this project since this issue seems specific to my project possibly.

**Comment by ItsAnysek** [comment]
Well, both files are located in bin/<your export os>/ (in this case windows). You could export the project and copy the files from there into your export destination folder.

**Comment by ItsAnysek** [comment]
> editor/export/editor_export_plugin.h:125 - Required virtual method EditorExportPlugin::_get_name must be overridden before calling

Also I think we should move this into it's own issue.
